resilience4j:
  retry:
    instances:
      retryAndRateLimitExample:
        maxRetryAttemps: 5
        waitDuration: 3s
  ratelimiter:
    instances:
      testRateLimiter: #name RateLimiter
        limitForPeriod: 2 # limit 2 request
        limitRefreshPeriod: 1s # trong 1s nhận 2 request
        timeoutDuration: 1s # quá limit thì sau 1s thì nhận lại request

      multipleRateLimiters_rps_limiter:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 2s

      multipleRateLimiters_rpm_limiter:
        limitForPeriod: 40
        limitRefreshPeriod: 1m
        timeoutDuration: 2s

      retryAndRateLimitExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms

      fallbackExample: #khi gọi lỗi trả  về phương thức khác
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms